added onboarding flow (no upload photo section for now)
SJSUCSClub/acm-website-client pull request #20
Opened 2024-10-20 04:16 UTC by raspberri05

https://github.com/user-attachments/assets/833070d6-bd28-4802-bce0-d806ca97cd46

2024-10-22 00:41 UTC, ManasC478 commented
The components look amazing. Just some things to change.
1. make the majors input a select instead of input because eventually you will fetch a list of majors from which the users can select
2. let's not add a 'other' options for status input. we don't need  year input and change 'status' to 'education level'
3. add input for grad_date. you can create your own component or use shadcn
4. let's add a interests input that can select multiple different interests. so they can select 'Web Dev', 'ML', 'Embedded' or more. The exact options are in the db_scripts/createdb.sql file as cs_fields_enum type at the top, in the server repo. you can make it a checkbox or dropdown checkbox.
5. let's remove 'team interest' input

2024-10-22 00:43 UTC, ManasC478 requested changes

2024-10-22 00:43 UTC, ManasC478 commented on src/components/atoms/card/component.tsx
> -export interface ICardProps extends React.ButtonHTMLAttributes<HTMLDivElement> {
checkout the comment i left in the discussion

2024-10-22 00:50 UTC, raspberri05 commented
> The components look amazing. Just some things to change.
> 
> 1. make the majors input a select instead of input because eventually you will fetch a list of majors from which the users can select
> 2. let's not add a 'other' options for status input. we don't need  year input and change 'status' to 'education level'
> 3. add input for grad_date. you can create your own component or use shadcn
> 4. let's add a interests input that can select multiple different interests. so they can select 'Web Dev', 'ML', 'Embedded' or more. The exact options are in the db_scripts/createdb.sql file as cs_fields_enum type at the top, in the server repo. you can make it a checkbox or dropdown checkbox.
> 5. let's remove 'team interest' input

Ok, i'll get to work on making those changes now

2024-10-23 01:28 UTC, raspberri05 commented
change to education level

status: required
major: required
grad date:required
purpose: optional
interests:optional
links:optional

2024-11-13 01:53 UTC, ManasC478 approved these changes

2024-11-13 01:55 UTC, merged