Restructure components into atomic structure
SJSUCSClub/acm-website-client pull request #7
Opened 2024-10-05 18:16 UTC by raspberri05

Restructured all existing components into atomic structure;

2024-10-05 20:11 UTC, ManasC478 requested changes
Seems like all the components have props type called Props. let's make them more specific like IBtnProps or ICardProps and also make sure to export them. Please check the other comments too. Nice Work.

2024-10-05 20:11 UTC, ManasC478 commented on src/components/molecules/link-card/component.tsx
> +);
let's move this to the atoms folder, since it doesn't use any atom components

2024-10-05 20:11 UTC, ManasC478 commented on src/components/organisms/footer/component.tsx
> +export const Footer: React.FC = () => (
let's move this component to atoms too.

2024-10-05 20:11 UTC, ManasC478 commented on src/components/organisms/mobile-menu/component.tsx
>    const handleClick = () => {
let's use the Btn component here instead of button. and let's move this to molecules

2024-10-05 20:11 UTC, ManasC478 commented on src/components/organisms/navbar/component.tsx
> +        <button
let's use btn component here

2024-10-05 20:11 UTC, ManasC478 commented on src/components/organisms/text-with-image/component.tsx
> +export const TextWithImage: React.FC<Props> = ({ children,
let's move this to atoms

2024-10-05 20:58 UTC, knhn1004 requested changes

2024-10-05 20:58 UTC, knhn1004 commented on package-lock.json
pull develop and try to use bun to run it

2024-10-05 20:58 UTC, knhn1004 commented on src/components/atoms/btn/component.tsx
> +);
add empty line below for these files with `-`

2024-10-05 20:59 UTC, knhn1004 commented on package-lock.json
first delete the existing `package-lock.json` and `node_modules`
then `bun install` `bun run dev`

2024-10-05 22:05 UTC, raspberri05 commented on package-lock.json
just tried running with bun and it worked

2024-10-05 22:09 UTC, raspberri05 commented on src/components/atoms/btn/component.tsx
> +);
where would i add `-`

2024-10-05 22:15 UTC, raspberri05 commented on src/components/organisms/navbar/component.tsx
> +        <button
👍🏽

2024-10-05 22:17 UTC, raspberri05 commented on src/components/organisms/mobile-menu/component.tsx
>    const handleClick = () => {
👍🏽

2024-10-06 02:15 UTC, knhn1004 commented on src/components/atoms/btn/component.tsx
> +);
no I meant if you go to `files` in this PR, you'll see there are files where there's a red `-` below, meaning there's a missing empty line in the end
you can add empty lines to those files

2024-10-06 02:25 UTC, raspberri05 commented on src/components/atoms/btn/component.tsx
> +);
made changes fixing this

2024-10-06 02:31 UTC, raspberri05 commented
I fixed the code based on the comments and requests to change - please let me know if anything else needs to be fixed or if it is good to merge

2024-10-07 18:53 UTC, ManasC478 approved these changes

2024-10-09 00:12 UTC, knhn1004 approved these changes

2024-10-09 01:00 UTC, merged